const { normalizeJob } = require('../normalize/job.cjs'); const { classifyApplicationMode } = require('../apply/application-mode.cjs'); const { fetchText } = require('../util/fetch.cjs'); const { unsupportedApply } = require('./interface.cjs'); const { stripHtml, cleanText, slugify, parseSinceDays } = require('../util/text.cjs');
const source={id:'web3-career',name:'Web3.career',supportsRemoteFilter:true,supportsNativeApply:false,supportsExternalApply:true,reviewOnly:true};
function buildSearchUrl({query='', remoteOnly=true}={}){ const q=cleanText(query).toLowerCase(); if(!q) return `https://web3.career/${remoteOnly?'remote-jobs':'web3-jobs'}`; const slug=q.split(/\s+/).map(encodeURIComponent).join('+'); return `https://web3.career/${slug}${remoteOnly?'+remote':''}-jobs`; }
function parseSalary(text=''){ const m=stripHtml(text).match(/\$\s?([0-9]{2,3})(?:k|,?000)?\s*-\s*\$?\s?([0-9]{2,3})(?:k|,?000)?/i); if(!m) return {}; return {salaryMin:Number(m[1])*1000, salaryMax:Number(m[2])*1000, currency:'USD'}; }
function queryMatches(text, query='') { const terms=cleanText(query).toLowerCase().split(/\s+/).filter(Boolean); if(!terms.length) return true; const t=String(text||'').toLowerCase(); return terms.every(term => t.includes(term)); }
function parseJobsFromHtml(html, opts={}){ const jobs=[]; const sinceDays=parseSinceDays(opts.since||'7d'); const rows=[...String(html).matchAll(/<tr[^>]+data-jobid=['"]?(\d+)['"]?[\s\S]*?<\/tr>/gi)].map(m=>({id:m[1],html:m[0]}));
  for(const row of rows){ if(jobs.length>=(opts.limit||25)) break; const h=row.html; const href=(h.match(/href=["']([^"']+\/\d+)["']/i)||[])[1]; const title=stripHtml((h.match(/<h2[^>]*>([\s\S]*?)<\/h2>/i)||[])[1]||''); const company=stripHtml((h.match(/<h3[^>]*>([\s\S]*?)<\/h3>/i)||[])[1]||'Unknown'); const dt=(h.match(/<time[^>]+datetime=["']([^"']+)["']/i)||[])[1]; const loc=stripHtml((h.match(/<td[^>]*job-location[^>]*>([\s\S]*?)<\/td>/i)||[])[1]||'Remote'); const text=stripHtml(h); if(!href||!title) continue; if(!queryMatches(`${title} ${company} ${text}`, opts.query||'')) continue; const postedAt=dt?new Date(dt).toISOString():undefined; if(postedAt && ((Date.now()-new Date(postedAt).getTime())/86400000)>sinceDays) continue; const sourceUrl=href.startsWith('http')?href:`https://web3.career${href}`; jobs.push(normalizeJob({id:`web3-career-${row.id}`,source:source.id,sourceUrl,applyUrl:sourceUrl,title,company,location:loc||'Remote',remote:/remote/i.test(text)||opts.remoteOnly!==false,remoteRegion:loc||'Unknown',tags:['web3'],applicationMode:classifyApplicationMode({applyUrl:sourceUrl}),descriptionText:text,status:'new',postedAt,...parseSalary(h)})); }
  return jobs; }
async function searchJobs(opts={}){ const url=buildSearchUrl(opts); const html=await fetchText(url,{headers:{'user-agent':'Mozilla/5.0 HermesRemoteJobs/0.1'}}); let jobs=parseJobsFromHtml(html, opts); if(!jobs.length && url!=='https://web3.career/remote-jobs'){ const fallback=await fetchText('https://web3.career/remote-jobs',{headers:{'user-agent':'Mozilla/5.0 HermesRemoteJobs/0.1'}}); jobs=parseJobsFromHtml(fallback, opts); } return jobs; }
async function getJobDetails(jobUrl){ return {sourceUrl:jobUrl}; }
async function getApplicationMode(job){ return classifyApplicationMode(job); }
module.exports={source,buildSearchUrl,parseJobsFromHtml,searchJobs,getJobDetails,getApplicationMode,applyToJob:unsupportedApply};
